### ISSUE TITLE
Create bridging.metadatacenter.org subdomain

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-bridge-server#3]
This subdomain will be used for all 3rd party integrations that use the bridge server. 

For example, https://bridging.metadatacenter.org/doi/datacite

**Comment by graybeal** [comment]
Bridging better than bridge?  if what it does is work with bridges, does consistency with all our other noun servers suggest bridge as the domain name?

**Comment by martinjoconnor** [comment]
We have bridge for the server side so were tying to main some parallelism (e.g., open/openview). 

Other suggestions welcome.

We would like to avoid creating a new subdomain for every bridged 3rd party to avoid  SSL cert creation and management issues.
